require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'LeanSdkExample' do
  config = use_native_modules!
  use_modular_headers!
  use_frameworks!
  use_react_native!(:path => config["reactNativePath"])

  pod "LeanSdk", :git => 'https://github.com/lean-app/lean-sdk-ios', :branch => '0.1.4'
  pod 'react-native-lean-sdk', :path => '../..'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  workspace 'LeanSdkExample.workspace'
  target 'RNLeanSdk' do
      project '../../ios/RNLeanSdk.xcodeproj'
      inherit! :search_paths
    end

  deployment_target = '11.0'

  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
              end
          end
          project.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
          end
      end
  end
end
